### ISSUE TITLE
SerialBT.read never return -1

### ISSUE THREAD

**Issue by softwarecrash** [avinabmalla/ESP32_BleSerial#14]
Great work,
but i noticed that the function `BleSerial::read()` never return a `-1` when no data avaible.
The Arduino Serial reference tells that `read()` return `-1` when no data.
can this be fixed?

**Comment by mspieth** [comment]
The issue is the use of uint8_t for the buffer pop. change in BleSerial.cpp read() result to int and the return type in pop and get in ByteRingBuffer. This fixes it.

**Comment by avinabmalla** [comment]
Fixed in v1.0.6
