### ISSUE TITLE
Compatibility with arduino-esp32 v3.0.0 : BLECharacteristic getValue std::string vs. String

### ISSUE THREAD

**Issue by PaulZC** [avinabmalla/ESP32_BleSerial#15]
Hi Avinab (@avinabmalla ),

Espressif made a breaking change to ```BLECharacteristic``` in this pull:

https://github.com/espressif/arduino-esp32/pull/8724

This means this line fails to compile with v3.0.0 of the core:

https://github.com/avinabmalla/ESP32_BleSerial/blob/9250e6724ab7edb6838460183820ebc47d0cf3a0/src/BleSerial.cpp#L167

Will you accept a Pull Request to change ```std::string``` to ```String```? Or is there a better way to solve this?

Thanks!
Paul (SparkFun)

**Comment by PaulZC** [comment]
Both std::string and String have c_str(). So one solution is:

```
		String value = pCharacteristic->getValue().c_str();
```

**Comment by avinabmalla** [comment]
Fixed in v1.0.5
