### ISSUE TITLE
Compilation error for the ESP32-C3 Dev Module

### ISSUE THREAD

**Issue by Ihor59** [avinabmalla/ESP32_BleSerial#7]
Compilation error for the ESP32-C3 Dev Module
Arduino 1.8.19
Expressive Systems 2.0.6

**Comment by hattesen** [comment]
@Ihor59 You couldn't provide a hint of the actual compilation error you experienced?
It would make it a lot easier to diagnose and resolve the issue ;)

**Comment by Ihor59** [comment]
Library Ok, problem was with Arduino IDE 1.8.19 how it organized libraries. I had to delete several other libraries before compilation error disappeared.
